language: go
sudo: required

services:
  - docker

go:
    - 1.6
    - tip

go_import_path: github.com/01org/ciao

# We need to create and install SSNTP certs for the SSNTP and controller tests
before_script:
   - sudo mkdir -p /etc/pki/ciao/
   - sudo -E $GOPATH/bin/ciao-cert -directory /etc/pki/ciao -host localhost -server -role scheduler
   - sudo -E $GOPATH/bin/ciao-cert -directory /etc/pki/ciao -host localhost -server-cert /etc/pki/ciao/cert-Scheduler-localhost.pem -role agent
   - sudo -E $GOPATH/bin/ciao-cert -directory /etc/pki/ciao -host localhost -server-cert /etc/pki/ciao/cert-Scheduler-localhost.pem -role controller
   - sudo cp /etc/pki/ciao/CAcert-localhost.pem /etc/pki/ciao/ca_cert.crt
   - sudo cp /etc/pki/ciao/CAcert-localhost.pem /etc/pki/ciao/CAcert-server-localhost.pem
   - sudo cp /etc/pki/ciao/cert-Scheduler-localhost.pem /etc/pki/ciao/server.pem
   - sudo cp /etc/pki/ciao/cert-CNAgent-localhost.pem /etc/pki/ciao/client.pem
   - sudo cp /etc/pki/ciao/cert-Controller-localhost.pem /etc/pki/ciao/cert-client-localhost.pem
   - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/ciao/ciao-controller-key.pem -out /etc/pki/ciao/ciao-controller-cacert.pem -subj '/CN=localhost/O=CIAO test server/C=US'
   - sudo cp /etc/pki/ciao/ciao-controller-cacert.pem /usr/local/share/ca-certificates/ciao-controller-cacert.crt
   - sudo update-ca-certificates

script:
   - go env
   - docker --version
   - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
   - docker --version
   - sudo docker pull debian
   - sudo ip link add testdummy type dummy
   - sudo ip addr add 198.51.100.1/24 dev testdummy
   - go get github.com/golang/lint/golint github.com/client9/misspell/cmd/misspell
   - go list ./... | grep -v vendor | xargs -t misspell
#  - go list ./... | grep -v vendor | xargs -t go vet
#  - go list ./... | grep -v vendor | xargs -tL 1 golint -set_exit_status
   - go vet github.com/01org/ciao/ciao-cli github.com/01org/ciao/ciao-controller/internal/datastore github.com/01org/ciao/ciao-controller/types github.com/01org/ciao/ciao-launcher github.com/01org/ciao/ciao-launcher/tests/ciao-launcher-server github.com/01org/ciao/ciao-launcher/tests/ciaolc github.com/01org/ciao/ciao-scheduler github.com/01org/ciao/networking/cnci_agent github.com/01org/ciao/networking/cnci_agent/test_cnci_server github.com/01org/ciao/networking/libsnnet github.com/01org/ciao/networking/libsnnet/tests/cncicli github.com/01org/ciao/networking/libsnnet/tests/cncli github.com/01org/ciao/networking/libsnnet/tests/docker/plugin github.com/01org/ciao/networking/libsnnet/tests/parallel github.com/01org/ciao/payloads github.com/01org/ciao/ssntp github.com/01org/ciao/ssntp/ciao-cert github.com/01org/ciao/test-cases
   - if [[ `go version | grep -v devel` ]] ; then go list github.com/01org/ciao/networking/... github.com/01org/ciao/ciao-controller github.com/01org/ciao/ciao-launcher/... github.com/01org/ciao/payloads github.com/01org/ciao/ssntp/... github.com/01org/ciao/test-cases github.com/01org/ciao/ciao-scheduler github.com/01org/ciao/ciao-cli | xargs -tL 1 golint -set_exit_status ; fi
   - test-cases -text github.com/01org/ciao/ciao-launcher github.com/01org/ciao/ciao-scheduler github.com/01org/ciao/ciao-controller/... github.com/01org/ciao/payloads
   - export GOROOT=`go env GOROOT` && sudo -E PATH=$PATH:$GOROOT/bin $GOPATH/bin/test-cases -text github.com/01org/ciao/ssntp
   - go get github.com/google/gofuzz
   - export GOROOT=`go env GOROOT` && export SNNET_ENV=198.51.100.0/24 && sudo -E PATH=$PATH:$GOROOT/bin $GOPATH/bin/test-cases -text -short -tags travis github.com/01org/ciao/networking/libsnnet
